export const SIGNUP = 'SIGNUP';
export const LOGIN = 'LOGIN';
// export const LOGOUT = 'LOGOUT'
export const EMAIL_OTP = 'EMAIL_OTP';
export const EMAIL_OTP_VERIFY = 'EMAIL_OTP_VERIFY';
export const PHONE_OTP = 'PHONE_OTP';
export const PHONE_OTP_VERIFY = 'PHONE_OTP_VERIFY';
export const PAYMENT = 'PAYMENT';
export const PAYMENT_BOOKING = 'PAYMENT_BOOKING';
export const CONFIRM_RIDE_ONLINE = 'CONFIRM_RIDE_ONLINE';
export const GETTESTIMONIAL = 'GETTESTIMONIAL';
export const GET_ABOUTCARDS = 'GET_ABOUTCARDS';
export const GET_CHOOSE = 'GET_CHOOSE';
export const GET_ABOUT = 'GET_ABOUT';
export const ADD_CONTACT = 'ADD_CONTACT';
