export const SIGNUP = 'SIGNUP'
export const LOGIN = 'LOGIN'
// export const LOGOUT = 'LOGOUT'
export const EMAIL_OTP = 'EMAIL_OTP'
// export const EMAIL_OTP_VERIFY = 'EMAIL_OTP_VERIFY'
export const PHONE_OTP = 'PHONE_OTP'
// export const PHONE_OTP_VERIFY = 'PHONE_OTP_VERIFY'